/control/verbose 2
/run/verbose 2
/run/initialize

/vis/open OGL 600x600-0+0

/vis/viewer/set/autoRefresh false
/vis/verbose errors

/vis/drawVolume

/vis/viewer/set/lightsThetaPhi 100. 150.
/vis/viewer/set/viewpointThetaPhi 100. 150.

/vis/viewer/set/style wireframe
/vis/viewer/set/auxiliaryEdge false
#/vis/viewer/set/lineSegmentsPerCircle 100

/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1

/vis/viewer/set/background 0.9 0.9 0.9

/vis/scene/endOfEventAction accumulate

/vis/viewer/set/autoRefresh true
/vis/verbose warnings
